// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GpYWnGxZLTb_cJG39C7DO6o8DNBJzSg',
    appId: '1:137733064772:web:bb7acd9553a533bb89d411',
    messagingSenderId: '137733064772',
    projectId: 'murshid-ec335',
    authDomain: 'murshid-ec335.firebaseapp.com',
    storageBucket: 'murshid-ec335.appspot.com',
    measurementId: 'G-ZJ25KQ9LQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1IxR17HZ3c3-_00Gv8StHxc8Jv04pOE',
    appId: '1:137733064772:android:30eeb04cc8c3200189d411',
    messagingSenderId: '137733064772',
    projectId: 'murshid-ec335',
    storageBucket: 'murshid-ec335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuk8utob9GZz_gwEziOZo2r1pFaS5Vgco',
    appId: '1:137733064772:ios:ea3600cbef3f155b89d411',
    messagingSenderId: '137733064772',
    projectId: 'murshid-ec335',
    storageBucket: 'murshid-ec335.appspot.com',
    iosBundleId: 'com.example.murshid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuk8utob9GZz_gwEziOZo2r1pFaS5Vgco',
    appId: '1:137733064772:ios:ea3600cbef3f155b89d411',
    messagingSenderId: '137733064772',
    projectId: 'murshid-ec335',
    storageBucket: 'murshid-ec335.appspot.com',
    iosBundleId: 'com.example.murshid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9GpYWnGxZLTb_cJG39C7DO6o8DNBJzSg',
    appId: '1:137733064772:web:af5c9727153e314389d411',
    messagingSenderId: '137733064772',
    projectId: 'murshid-ec335',
    authDomain: 'murshid-ec335.firebaseapp.com',
    storageBucket: 'murshid-ec335.appspot.com',
    measurementId: 'G-3L54GR6LXG',
  );
}
